version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11  # Use the appropriate Java version

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Check out your source code
      
      - run:
          name: Install Maven
          command: |
            curl -s https://apache.osuosl.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz | tar -xz -C /opt
            echo 'export PATH=/opt/apache-maven-3.8.6/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      
      - run:
          name: Build with Maven
          command: mvn clean install  # Adjust if you need to run tests or a specific phase

workflows:
  version: 2
  build:
    jobs:
      - build
